### 회원가입 (고객)
POST http://localhost:8081/signup/customer
Content-Type: application/json

{
  "birth": "1990-08-17",
  "email": "duketest@gmail.com",
  "name": "이름",
  "password": "pw",
  "phone": "000-0001-1234"
}

### 이메일 인증 (고객)
GET http://localhost:8081/signup/customer/verify?email=duketest@gmail.com&code=XRch3mJtX9

### 로그인(고객)
POST http://localhost:8081/signin/customer
Content-Type: application/json

{
  "email": "duketest@gmail.com",
  "password": "pw"
}

### 회원정보 조회 (고객)
#eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJFZkRyRDR4Mm9BRXpvTzNsbW1sWHlQUUpCYnplMmxoZlRUbEJSVFF4UytFPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2NzM5NDM4OTcsImV4cCI6MTY3NDAzMDI5N30.OwUOWuOmHJ7QOGA9SPjXmSOhZK3nPGd7nQnZktJFeyo
GET http://localhost:8081/customer/getInfo
Content-Type: application/json
X-AUTH-TOKEN:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJFZkRyRDR4Mm9BRXpvTzNsbW1sWHlQUUpCYnplMmxoZlRUbEJSVFF4UytFPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2NzM5NDM4OTcsImV4cCI6MTY3NDAzMDI5N30.OwUOWuOmHJ7QOGA9SPjXmSOhZK3nPGd7nQnZktJFeyo

### 잔액변경 (고객)
POST http://localhost:8081/customer/balance
Content-Type: application/json
X-AUTH-TOKEN:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJFZkRyRDR4Mm9BRXpvTzNsbW1sWHlQUUpCYnplMmxoZlRUbEJSVFF4UytFPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2NzM5NDM4OTcsImV4cCI6MTY3NDAzMDI5N30.OwUOWuOmHJ7QOGA9SPjXmSOhZK3nPGd7nQnZktJFeyo

{
  "from": "duketest@gmail.com",
  "message": "돈 충전",
  "money": 50000
}


##########################################
### 회원가입 (셀러)
POST http://localhost:8081/signup/seller
Content-Type: application/json

{
  "birth": "1990-08-17",
  "email": "duketest@gmail.com",
  "name": "이름",
  "password": "pw",
  "phone": "000-0001-1234"
}

### 이메일 인증 (셀러)
GET http://localhost:8081/signup/seller/verify?email=duketest@gmail.com&code=hZ03j0tCn4

### 로그인(셀러)
POST http://localhost:8081/signin/seller
Content-Type: application/json

{
  "email": "duketest@gmail.com",
  "password": "pw"
}
