### 상품추가 (셀러)
POST http://localhost:8082/seller/product
Content-Type: application/json
X_AUTH_TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJFZkRyRDR4Mm9BRXpvTzNsbW1sWHlQUUpCYnplMmxoZlRUbEJSVFF4UytFPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjczODEwNzA1LCJleHAiOjE2NzM4OTcxMDV9.ejHFu1CA0Le_pbdA4_GULqvno1D26ZOcAfJMk1VU5qo



{
  "description": "상품설명생성",
  "items": [
    {
      "count": 1,
      "name": "260",
      "price": 1
    }
  ],
  "name": "나이키"
}

### 상품 아이템 추가
POST http://localhost:8082/seller/product/item
Content-Type: application/json
X_AUTH_TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJFZkRyRDR4Mm9BRXpvTzNsbW1sWHlQUUpCYnplMmxoZlRUbEJSVFF4UytFPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjczODEwNzA1LCJleHAiOjE2NzM4OTcxMDV9.ejHFu1CA0Le_pbdA4_GULqvno1D26ZOcAfJMk1VU5qo


{
  "productId": 1,
  "count": 10,
  "name": "275",
  "price": 10001
}

### 상품수정
PUT http://localhost:8082/seller/product
Content-Type: application/json
X_AUTH_TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJFZkRyRDR4Mm9BRXpvTzNsbW1sWHlQUUpCYnplMmxoZlRUbEJSVFF4UytFPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjczODEwNzA1LCJleHAiOjE2NzM4OTcxMDV9.ejHFu1CA0Le_pbdA4_GULqvno1D26ZOcAfJMk1VU5qo


{
  "id" : 1,
  "name": "나이키 수정3",
  "description": "상품설명수정3",
  "items": [
    {
      "id": 1,
      "count": 100,
      "name": "280",
      "price": 10
    }
  ]
}

### 상품 아이템 수정
PUT http://localhost:8082/seller/product/item
Content-Type: application/json
X_AUTH_TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJFZkRyRDR4Mm9BRXpvTzNsbW1sWHlQUUpCYnplMmxoZlRUbEJSVFF4UytFPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjczODEwNzA1LCJleHAiOjE2NzM4OTcxMDV9.ejHFu1CA0Le_pbdA4_GULqvno1D26ZOcAfJMk1VU5qo


{
  "id": 3,
  "count": 1020,
  "name": "아이템수정",
  "price": 2
}


### 상품삭제
DELETE http://localhost:8082/seller/product?id=1
Content-Type: application/json
X_AUTH_TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJFZkRyRDR4Mm9BRXpvTzNsbW1sWHlQUUpCYnplMmxoZlRUbEJSVFF4UytFPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjczODEwNzA1LCJleHAiOjE2NzM4OTcxMDV9.ejHFu1CA0Le_pbdA4_GULqvno1D26ZOcAfJMk1VU5qo


{
  "description": "상품설명수정",
  "items": [
    {
      "id": 1,
      "count": 100,
      "name": "280",
      "price": 10
    }
  ],
  "id" : 1,
  "name": "나이키 수정"
}

### 상품 아이템 삭제
DELETE http://localhost:8082/seller/product/item?id=2
Content-Type: application/json
X_AUTH_TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJFZkRyRDR4Mm9BRXpvTzNsbW1sWHlQUUpCYnplMmxoZlRUbEJSVFF4UytFPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjczODEwNzA1LCJleHAiOjE2NzM4OTcxMDV9.ejHFu1CA0Le_pbdA4_GULqvno1D26ZOcAfJMk1VU5qo


{
  "id": 2
}

### 상품 아이템 검색
GET http://localhost:8082/search/product?name=나이키
Content-Type: application/json

### 상품 디테일 검색
GET http://localhost:8082/search/product/detail?productId=2
Content-Type: application/json


### 카트추가
POST http://localhost:8082/customer/cart
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJFZkRyRDR4Mm9BRXpvTzNsbW1sWHlQUUpCYnplMmxoZlRUbEJSVFF4UytFPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjczODEwNzA1LCJleHAiOjE2NzM4OTcxMDV9.ejHFu1CA0Le_pbdA4_GULqvno1D26ZOcAfJMk1VU5qo

{
  "description": "상품설명생성",
  "id": 3,
  "items": [
    {
      "count": 1,
      "id": 3,
      "name": "260",
      "price": 1
    }
  ],
  "name": "나이키",
  "sellerId": 1
}